// Auto-generated by pipeline/import_study_results.py — do not hand-edit.
// Source: results/multi_model/multi_model_study.json

export type Vendor = "kimi" | "claude" | "gemini";

export interface VendorMeta {
  id: Vendor;
  displayName: string;
  shortName: string;
  modelId: string;
  vendor: string;
  accentText: string;
  accentBg: string;
  accentBorder: string;
  accentHex: string;
}

export const VENDORS: Record<Vendor, VendorMeta> = {
  kimi: {
    id: "kimi",
    displayName: "Kimi K2",
    shortName: "Kimi",
    modelId: "moonshotai/kimi-k2-instruct",
    vendor: "Moonshot AI · NVIDIA NIM",
    accentText: "text-[#F59E0B]",
    accentBg: "bg-[#F59E0B]/15",
    accentBorder: "border-[#F59E0B]",
    accentHex: "#F59E0B",        // amber
  },
  claude: {
    id: "claude",
    displayName: "Claude Sonnet 4.6",
    shortName: "Claude",
    modelId: "us.anthropic.claude-sonnet-4-5-20250929-v1:0",
    vendor: "Anthropic · AWS Bedrock",
    accentText: "text-[#D97757]",
    accentBg: "bg-[#D97757]/15",
    accentBorder: "border-[#D97757]",
    accentHex: "#D97757",        // warm coral-clay (Anthropic-ish)
  },
  gemini: {
    id: "gemini",
    displayName: "Gemini 3.1 Pro Preview",
    shortName: "Gemini",
    modelId: "gemini-3.1-pro-preview",
    vendor: "Google · Vertex AI",
    accentText: "text-[#3B82F6]",
    accentBg: "bg-[#3B82F6]/15",
    accentBorder: "border-[#3B82F6]",
    accentHex: "#3B82F6",        // google blue
  },
};

export interface VendorEffect {
  vendor: Vendor;
  zeroMean: number;
  engineeredMean: number;
  delta: number;
  deltaSE: number;
  pValue: number;
  cohenD: number;
  successRateZero: number;
  successRateEng: number;
  n: number;
}

export const VENDOR_EFFECTS: VendorEffect[] = [
  { vendor: "kimi", zeroMean: 2.505, engineeredMean: 3.115, delta: 0.61, deltaSE: 0.061, pValue: 1e-12, cohenD: 0.704, successRateZero: 0.535, successRateEng: 0.765, n: 200 },
  { vendor: "claude", zeroMean: 3.025, engineeredMean: 3.37, delta: 0.345, deltaSE: 0.041, pValue: 1e-12, cohenD: 0.594, successRateZero: 0.69, successRateEng: 0.83, n: 200 },
  { vendor: "gemini", zeroMean: 2.48, engineeredMean: 3.165, delta: 0.685, deltaSE: 0.06, pValue: 1e-12, cohenD: 0.802, successRateZero: 0.525, successRateEng: 0.765, n: 200 },
];

export const KAPPA_MATRIX: number[][] = [
  [1.0, 0.431, 0.388],
  [0.431, 1.0, 0.431],
  [0.388, 0.431, 1.0],
];

export const KAPPA_LABELS: Vendor[] = ["kimi", "claude", "gemini"];

export interface LanguageEffect { language: string; n: number; kimi: number; claude: number; gemini: number; }

export const LANGUAGE_EFFECTS: LanguageEffect[] = [
  { language: "Python", n: 68, kimi: 0.647, claude: 0.471, gemini: 0.735 },
  { language: "TypeScript", n: 62, kimi: 0.532, claude: 0.145, gemini: 0.694 },
  { language: "JavaScript", n: 27, kimi: 0.519, claude: 0.333, gemini: 0.852 },
  { language: "C++", n: 14, kimi: 0.857, claude: 0.429, gemini: 0.857 },
  { language: "Java", n: 14, kimi: 0.571, claude: 0.429, gemini: 0.357 },
  { language: "Go", n: 8, kimi: 1.0, claude: 0.75, gemini: 0.25 },
  { language: "Rust", n: 7, kimi: 0.429, claude: 0.143, gemini: 0.286 },
];

export const STUDY_META = {
  totalConversations: 200,
  totalOutputs: 1200,
  vendors: 3,
  modes: 2,
  judgeModel: "Claude Sonnet 4.6 (rubric-based)",
  rubricMaxScore: 4,
  isPlaceholder: false,
};
